import * as React from 'react';
import { useState } from 'react';
import { 
  FileText, AlertTriangle, Share2, Edit3, 
  ArrowLeft, Briefcase, TrendingUp, ShieldAlert, 
  BadgeCheck 
} from 'lucide-react';
import { Rfp, TechnicalAgentOutput, FinancialAgentResult, BlankDoc } from '../../types';
import jsPDF from 'jspdf';
import 'jspdf-autotable';

interface FinalRecommendationProps {
  rfp: Rfp;
  analysisContext?: any; // The bridged data from AnalysisScreen
  onBack: () => void;
  onCancel: () => void;
}

export const FinalRecommendation: React.FC<FinalRecommendationProps> = ({ rfp, analysisContext, onBack, onCancel }) => {
  const [remarks, setRemarks] = useState<string>('');
  const [isEditing, setIsEditing] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);

  // --- 1. DATA EXTRACTION & FALLBACKS ---
  const technical = rfp.agentOutputs?.technicalAnalysis as TechnicalAgentOutput;
  const financial = rfp.agentOutputs?.pricing as FinancialAgentResult;
  
  // Fetch risks from our updated App.tsx mapping or fallback
  const riskList = rfp.agentOutputs?.parsedData?.riskAnalysis || financial?.riskEntries || [];
  
  // Dynamic Data from Context
  const calc = analysisContext?.liveCalculations || {};
  const docs = analysisContext?.blankDocs || [];
  const marginPercent = analysisContext?.profitMargin || 15;
  const logisticsPercent = calc.materialBase ? ((calc.logistics / calc.materialBase) * 100).toFixed(1) : 0;
  const finalValue = calc.finalTotal || financial?.summary?.finalBidValue || 0;

  // --- 2. VERDICT LOGIC ---
  const calculateScore = () => {
    if (!technical || !financial) return 0;
    const techScore = technical.itemAnalyses.reduce((acc, item) => acc + (item.selectedSku?.matchPercentage || 0), 0) / (technical.itemAnalyses.length || 1);
    const finScore = Math.min(marginPercent * 5, 100); 
    const riskScore = riskList.some((r: any) => r.riskLevel === 'High') ? 0 : riskList.some((r: any) => r.riskLevel === 'Medium') ? 50 : 100;
    return Math.round((techScore * 0.5) + (finScore * 0.3) + (riskScore * 0.2));
  };

  const bidScore = calculateScore();
  const verdict = bidScore >= 70 ? 'BID' : bidScore >= 40 ? 'REVIEW' : 'NO-BID';

  // --- 3. MULTI-PAGE PDF GENERATOR ENGINE ---
  const handleGeneratePdf = () => {
    setIsGenerating(true);
    
    setTimeout(() => {
      try {
        const doc = new jsPDF();
        
        // PAGE 1: EXECUTIVE SUMMARY & RISKS
        doc.setFontSize(22);
        doc.setTextColor(40, 40, 40);
        doc.text("Executive Bid Summary", 14, 22);
        
        doc.setFontSize(11);
        doc.setTextColor(100, 100, 100);
        doc.text(`Generated by TenderFlow on ${new Date().toLocaleDateString()}`, 14, 30);
        
        doc.setTextColor(0, 0, 0);
        doc.text(`Tender ID: ${rfp.id}`, 14, 40);
        doc.text(`Organization: ${rfp.organisation}`, 14, 46);
        doc.text(`System Verdict: ${verdict} (Score: ${bidScore}/100)`, 14, 52);
        
        if (remarks) {
          doc.text(`Executive Remarks: ${remarks}`, 14, 62, { maxWidth: 180 });
        }

        doc.setFontSize(16);
        doc.text("Risk Assessment Matrix", 14, remarks ? 85 : 75);
        const riskData = riskList.length > 0 
          ? riskList.map((r: any) => [r.category, r.riskLevel, r.statement])
          : [['System', 'Low', 'No significant risks identified during analysis.']];
        
        (doc as any).autoTable({
          startY: remarks ? 90 : 80,
          head: [['Category', 'Risk Level', 'Statement']],
          body: riskData,
          theme: 'grid',
          headStyles: { fillColor: [220, 38, 38] },
          styles: { fontSize: 9 }
        });

        // PAGE 2: TECHNICAL MATCHING
        doc.addPage();
        doc.setFontSize(16);
        doc.text("Technical Compliance & SKUs", 14, 22);
        
        const techData = technical?.itemAnalyses.map(item => [
          item.rfpLineItem.name,
          item.rfpLineItem.quantity,
          item.selectedSku?.skuId || "N/A",
          item.selectedSku?.productName || "No Exact Match",
          `${item.selectedSku?.matchPercentage || 0}%`
        ]) || [];

        (doc as any).autoTable({
          startY: 30,
          head: [['RFP Requirement', 'Qty', 'SKU', 'Internal Product', 'Match %']],
          body: techData,
          theme: 'grid',
          headStyles: { fillColor: [37, 99, 235] },
          styles: { fontSize: 9 }
        });

        // PAGE 3: FINANCIAL BREAKDOWN
        doc.addPage();
        doc.setFontSize(16);
        doc.text("Financial Projections", 14, 22);

        const finData = [
          ["Base Material Cost", `Rs. ${Math.round(calc.materialBase || 0).toLocaleString()}`],
          ["Logistics & Buffer", `Rs. ${Math.round(calc.logistics || 0).toLocaleString()}`],
          ["Total GST", `Rs. ${Math.round(calc.gst || 0).toLocaleString()}`],
          ["GeM Brokerage Fee", `Rs. ${Math.round(calc.gemFee || 0).toLocaleString()}`],
          ["Required EMD Provision", `Rs. ${Math.round(calc.emd || 0).toLocaleString()}`],
          ["Required EPBG Provision", `Rs. ${Math.round(calc.epbg || 0).toLocaleString()}`],
          [`Net Profit (${marginPercent}%)`, `Rs. ${Math.round(calc.profit || 0).toLocaleString()}`],
          ["FINAL AUTHORIZED BID", `Rs. ${Math.round(finalValue).toLocaleString()}`]
        ];

        (doc as any).autoTable({
          startY: 30,
          head: [['Cost Component', 'Calculated Amount']],
          body: finData,
          theme: 'grid',
          headStyles: { fillColor: [16, 185, 129] },
          styles: { fontSize: 10 }
        });

        doc.save(`TenderFlow_Executive_${rfp.id}.pdf`);
      } catch (err) {
        console.error("PDF Generation Error", err);
        alert("Failed to generate PDF Report.");
      } finally {
        setIsGenerating(false);
      }
    }, 500); // Small timeout to allow UI button state to update
  };

  return (
    <div className="absolute inset-0 bg-slate-950 flex flex-col font-sans">
      
      {/* HEADER (FIXED) */}
      <div className="shrink-0 flex items-center justify-between bg-slate-900/40 p-6 border-b border-slate-800 backdrop-blur-xl z-20">
        <div className="flex items-center gap-4">
          <button onClick={onBack} className="p-2 hover:bg-slate-800 rounded-full transition-colors">
            <ArrowLeft className="w-6 h-6 text-slate-400" />
          </button>
          <div>
            <h1 className="text-2xl font-bold text-white tracking-tight flex items-center gap-3">
              Final Recommendation
              <span className={`px-3 py-1 rounded-full text-[10px] font-black uppercase tracking-widest border ${
                verdict === 'BID' ? 'bg-emerald-500/10 border-emerald-500 text-emerald-400' :
                verdict === 'REVIEW' ? 'bg-amber-500/10 border-amber-500 text-amber-400' :
                'bg-red-500/10 border-red-500 text-red-400'
              }`}>
                {verdict} Recommended
              </span>
            </h1>
            <p className="text-xs text-slate-500 font-mono mt-1">REF: {rfp.id} • {rfp.organisation}</p>
          </div>
        </div>
      </div>

      {/* SCROLLABLE MAIN CONTENT */}
      <div className="flex-grow overflow-y-auto scrollbar-hide px-8 pt-8 pb-32 relative z-10">
        <div className="grid grid-cols-12 gap-6 max-w-[1600px] mx-auto">
          
          {/* LEFT COL: ANALYSIS SUMMARY (8 Cols) */}
          <div className="col-span-12 lg:col-span-8 flex flex-col gap-6">
            
            {/* 1. TECHNICAL MATCH CARD */}
            <div className="bg-slate-900/40 border border-slate-800 rounded-3xl p-6 backdrop-blur-sm shadow-xl">
              <div className="flex items-center justify-between mb-6">
                <h3 className="text-sm font-black text-slate-400 uppercase tracking-widest flex items-center gap-2">
                  <BadgeCheck className="w-4 h-4 text-emerald-500" /> Technical Feasibility
                </h3>
                <span className="text-2xl font-bold text-white">{Math.round(bidScore)}<span className="text-sm text-slate-500">/100</span></span>
              </div>

              <div className="space-y-4">
                {technical?.itemAnalyses.map((item, idx) => (
                  <div key={idx} className="flex items-center justify-between p-4 bg-slate-950 rounded-2xl border border-slate-800/50">
                    <div className="flex items-center gap-4">
                      <div className="w-10 h-10 rounded-lg bg-slate-900 flex items-center justify-center font-bold text-slate-500">
                        {idx + 1}
                      </div>
                      <div>
                        <p className="text-sm font-bold text-white">{item.rfpLineItem.name}</p>
                        <p className="text-xs text-slate-500">Matched: <span className="text-blue-400">{item.selectedSku?.productName || "No Match"}</span></p>
                      </div>
                    </div>
                    <div className="text-right">
                      <div className={`text-lg font-bold ${
                        (item.selectedSku?.matchPercentage || 0) > 80 ? 'text-emerald-400' : 'text-amber-400'
                      }`}>
                        {item.selectedSku?.matchPercentage || 0}%
                      </div>
                      <p className="text-[10px] text-slate-600 uppercase font-bold">Spec Match</p>
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {/* 2. RISK & REMARKS */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              {/* Risk Factors */}
              <div className="bg-slate-900/40 border border-slate-800 rounded-3xl p-6 shadow-xl">
                <h3 className="text-sm font-black text-slate-400 uppercase tracking-widest mb-4 flex items-center gap-2">
                  <ShieldAlert className="w-4 h-4 text-amber-500" /> Risk Assessment
                </h3>
                <div className="space-y-3">
                  {riskList.length > 0 ? riskList.map((risk: any, i: number) => (
                    <div key={i} className="flex gap-3 items-start p-3 bg-slate-950/50 rounded-xl border border-slate-800">
                      <AlertTriangle className={`w-4 h-4 mt-0.5 shrink-0 ${
                        risk.riskLevel === 'High' ? 'text-red-500' : 'text-amber-500'
                      }`} />
                      <div>
                        <p className="text-xs font-bold text-slate-300">{risk.category} Risk</p>
                        <p className="text-[10px] text-slate-500 leading-tight mt-1">{risk.statement}</p>
                      </div>
                    </div>
                  )) : (
                    <div className="text-center py-8 text-slate-600 text-xs italic">No significant risks detected in analysis.</div>
                  )}
                </div>
              </div>

              {/* Editable Remarks */}
              <div className="bg-slate-900/40 border border-slate-800 rounded-3xl p-6 flex flex-col shadow-xl">
                <div className="flex justify-between items-center mb-4">
                  <h3 className="text-sm font-black text-slate-400 uppercase tracking-widest flex items-center gap-2">
                    <Edit3 className="w-4 h-4 text-blue-500" /> Executive Remarks
                  </h3>
                  <button 
                    onClick={() => setIsEditing(!isEditing)} 
                    className="text-[10px] font-bold text-blue-400 hover:text-white transition-colors uppercase"
                  >
                    {isEditing ? 'Save Note' : 'Edit'}
                  </button>
                </div>
                
                {isEditing ? (
                  <textarea 
                    value={remarks}
                    onChange={(e) => setRemarks(e.target.value)}
                    placeholder="Enter final decision rationale..."
                    className="flex-grow w-full bg-slate-950 border border-slate-700 rounded-xl p-3 text-sm text-white focus:border-blue-500 outline-none resize-none"
                  />
                ) : (
                  <div className="flex-grow bg-slate-950/50 rounded-xl p-4 border border-slate-800 text-sm text-slate-400 italic">
                    {remarks || "No additional remarks added. Click Edit to add operator context."}
                  </div>
                )}
              </div>
            </div>
          </div>

          {/* RIGHT COL: FINANCIALS & DOCS (4 Cols) */}
          <div className="col-span-12 lg:col-span-4 flex flex-col gap-6">
            
            {/* 1. FINANCIAL SUMMARY */}
            <div className="bg-gradient-to-b from-slate-900 to-slate-950 border border-slate-800 rounded-3xl p-6 relative overflow-hidden shadow-xl">
              <div className="absolute top-0 right-0 w-32 h-32 bg-gold-500/10 blur-[50px] rounded-full pointer-events-none" />
              
              <h3 className="text-sm font-black text-gold-500 uppercase tracking-widest mb-6 flex items-center gap-2">
                <TrendingUp className="w-4 h-4" /> Final Projections
              </h3>

              <div className="space-y-6">
                <div>
                  <p className="text-xs text-slate-500 font-bold uppercase tracking-wider">Est. Contract Value</p>
                  <p className="text-3xl font-mono font-bold text-white mt-1">
                    ₹{Math.round(finalValue).toLocaleString()}
                  </p>
                </div>

                <div className="grid grid-cols-2 gap-4">
                  <div className="p-3 bg-slate-800/50 rounded-xl border border-slate-700">
                    <p className="text-[10px] text-slate-400 uppercase">Margin</p>
                    <p className="text-lg font-bold text-emerald-400">{marginPercent}%</p>
                  </div>
                  <div className="p-3 bg-slate-800/50 rounded-xl border border-slate-700">
                    <p className="text-[10px] text-slate-400 uppercase">Logistics Cost</p>
                    <p className="text-lg font-bold text-slate-200">{logisticsPercent}%</p>
                  </div>
                </div>

                <div className="pt-4 border-t border-slate-800">
                  <p className="text-[10px] text-slate-500 mb-2">Confidence Score</p>
                  <div className="h-2 w-full bg-slate-800 rounded-full overflow-hidden">
                    <div 
                      className="h-full bg-gradient-to-r from-blue-600 to-emerald-400" 
                      style={{ width: `${financial?.summary?.confidenceScore || 75}%` }}
                    />
                  </div>
                </div>
              </div>
            </div>

            {/* 2. DYNAMIC DOCUMENT HUB */}
            <div className="flex-grow bg-slate-900/40 border border-slate-800 rounded-3xl p-6 flex flex-col shadow-xl">
              <h3 className="text-sm font-black text-slate-400 uppercase tracking-widest mb-6 flex items-center gap-2">
                <Briefcase className="w-4 h-4 text-blue-500" /> Exportable Documents
              </h3>

              <div className="space-y-3 flex-grow overflow-y-auto max-h-[300px] scrollbar-hide pr-2">
                {docs.length > 0 ? docs.map((doc: BlankDoc, i: number) => (
                   <div key={i} className="group flex flex-col p-4 bg-slate-950 border border-slate-800 rounded-2xl">
                      <div className="flex items-center gap-3 mb-3">
                        <div className={`p-2 rounded-lg ${doc.status === 'CONVERTED_TO_DOCX' ? 'bg-emerald-900/20 text-emerald-400' : 'bg-slate-800 text-slate-400'}`}>
                          <FileText className="w-5 h-5" />
                        </div>
                        <div>
                          <p className="text-xs font-bold text-white line-clamp-1">{doc.name}</p>
                          <p className="text-[9px] text-slate-500 uppercase tracking-widest">{doc.status === 'CONVERTED_TO_DOCX' ? 'Word Document' : 'Original PDF'}</p>
                        </div>
                      </div>
                      
                      {doc.status === 'CONVERTED_TO_DOCX' ? (
                        <button 
                          onClick={() => { if(doc.docxUrl) window.open(doc.docxUrl, '_blank'); }} 
                          className="w-full py-2 bg-emerald-500/10 border border-emerald-500/30 text-emerald-400 hover:bg-emerald-500 hover:text-white rounded-xl text-[9px] font-black uppercase tracking-widest transition-all"
                        >
                          Download & Edit
                        </button>
                      ) : (
                        <button 
                          onClick={() => window.open(doc.url, '_blank')} 
                          className="w-full py-2 bg-slate-800 text-slate-300 hover:bg-slate-700 hover:text-white rounded-xl text-[9px] font-black uppercase tracking-widest transition-all"
                        >
                          Preview File
                        </button>
                      )}
                   </div>
                )) : (
                  <div className="text-center py-8 text-slate-600 text-xs italic border border-dashed border-slate-800 rounded-xl">
                     No documents forwarded from analysis.
                  </div>
                )}
              </div>
            </div>

          </div>
        </div>
      </div>

      {/* FIXED BOTTOM ACTION BAR */}
      <div className="absolute bottom-0 left-0 right-0 h-24 bg-slate-950/90 backdrop-blur-xl border-t border-slate-800/80 flex items-center justify-between px-8 z-50">
         <button onClick={onCancel} className="bg-slate-800 text-slate-300 border border-slate-700 hover:bg-slate-700 hover:text-white px-6 py-3.5 rounded-xl text-[10px] font-black uppercase tracking-widest transition-all">
            Abort Process
         </button>
         
         <button 
            onClick={handleGeneratePdf}
            disabled={isGenerating}
            className="flex items-center gap-3 px-8 py-4 bg-gold-500 hover:bg-white text-slate-950 rounded-xl shadow-[0_0_20px_rgba(212,175,55,0.3)] transition-all text-xs font-black uppercase tracking-widest disabled:opacity-50"
         >
            {isGenerating ? 'Exporting PDF...' : <><Share2 className="w-4 h-4" /> Export Executive Report</>}
         </button>
      </div>

      <style>{`.scrollbar-hide::-webkit-scrollbar { display: none; }`}</style>
    </div>
  );
};